twig:
    file_name_pattern: '*.twig'
    
when@test:
    twig:
        strict_variables: true

when@dev:
    # Easiest way to display the template sources in the examples
    # -- For development purpose ONLY --
    twig:
        paths:
            "doc/examples/": "example"
